ministryofjustice/opg-metrics

terraform/environment/api/openapi_spec.json

AWS does not completely conform to OpenAPI standards. The use of default responses has caused issues when defined in a schema. This fix removes it.
Fixes Ticket: MET-30
Manually imported the existing OpenAPI schema into API Gateway, saw this failed and made amends as needed for it to pass on import.
We need to find the best way to validate against the capabilities of API Gateway on future changes. Or as discussed with @andrewpearce-digital potentially having a development environment be deployed on PRs to see breaking changes before going to live.

Fixes AWS openapi configuration

---

terraform/environment/api-gateway.tf
terraform/environment/api/openapi_spec.json

Stages within TF were not being published after being applied and there are some rogue test resources being created.
Fixes Ticket: MET-32
Set the correct resources for prod and dev stages and ensure they trigger a deployment to set them as the current stage instead of just adding to the history of the stage.

MET-32 Removes test resource and correctly sets stage deployments

---

scripts/pipeline/post_to_api/post_to_api.py
terraform/environment/api/openapi_spec.json

Removes the need for 2 authentication methods to just use an api key rather than AWS4Auth
Removes the definition from the open api spec and the test script

Removes AWS4Auth from securityDefinitions

---

terraform/environment/api/openapi_spec.json

Changes the limit on a metric from 15 to 25 characters
Real life usage needs greater field length options in metric data being passed. This updates the max length in the API spec.

Changes the limit on a metric from 15 to 25 characters

---

terraform/environment/dns.tf

We get the following error currently when building the infra
```
Error: Error creating API Gateway Domain Name: BadRequestException: Invalid certificate ARN: arn:aws:acm:eu-west-1:679638075911:certificate/b7f2e63f-c53a-48b5-b86d-f0a54a39a6cf. Certificate must be in 'us-east-1'.
on dns.tf line 18, in resource "aws_api_gateway_domain_name" "opg_metrics":
18: resource "aws_api_gateway_domain_name" "opg_metrics" {
```
We actually need to specify that it should be regional instead of edge by default, otherwise certs from us-east-1 can only be used.
Explained above

Specify regional api gateway domain name

---

terraform/environment/api-keys.tf
terraform/environment/dns.tf

The certificate generated for the API gateway should be assigned as a regional cert.

Change api gateway domain cert to be regional

---

terraform/environment/api/examples/put_metrics.json
terraform/environment/api/openapi_spec.json

Adds the OpenAPI optional parameter Environment to be sent with Metrics
Fixes Ticket: UML-1605
Add the property to the OpenAPI Spec to be consumed by API Gateway

Add Environment option to metric data

---

terraform/environment/api/openapi_spec.json

Allow larger values (such as aws service names, cost values) to be passed in to the service validation

Increase length of certain properties to allow larger values

---

terraform/environment/api/openapi_spec.json

Allow numbers within the metric values to cover things like EC2 & S3

allow numbers in the regexs

---

terraform/environment/api/openapi_spec.json

Updates from swagger to OpenAPI 3 and fixes the validation rules not being set in API Gateway even though they are defined in the spec.

Update to OpenAPI 3, fix request validator

---

.circleci/config.yml

Automate a security stance by replacing API keys on a regular basis.
Fixes Ticket: UML-1871
- Create a new job lists api keys in terraform state and taints them
- Add a workflow that runs the taint and apply jobs on a schedule
- https://circleci.com/docs/2.0/configuration-reference/#schedule
- https://www.terraform.io/docs/cli/commands/taint.html

UML-1871 - Rotate API Keys on a schedule

---

.circleci/config.yml
lambda/clsf-to-sqs/src/requirements_dev.txt
lambda/clsf-to-sqs/src/test_main.py
lambda/ship-to-opg-metrics/src/requirements_dev.txt

Adds the python tests to the CI pipeline on a PR build for both lambdas
Fixes Ticket: UML-1988
Followed existing pattern in CircleCI config for installing requirements and running replicating local method.

Uml 1988 enable pytest ci

---

lambda/ship-to-opg-metrics/src/main.py
lambda/ship-to-opg-metrics/src/requirements.txt
lambda/ship-to-opg-metrics/src/requirements_dev.txt

add request tracing to the ship-to-metrics lambda function code
Fixes Ticket: UML-2091
- https://docs.aws.amazon.com/lambda/latest/dg/python-tracing.html
- https://pypi.org/project/aws-xray-sdk/
- https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html
- https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-annotations
* ~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* ~I have added tests to prove my work~
* ~The product team have tested these changes~

UML-2091 - instrument for xray

---

.github/workflows/apache-flink.yml
.github/workflows/apache_flink_job.yml
.github/workflows/data-parse-branch-name.yml
.github/workflows/path_to_live_workflow.yml
.github/workflows/pr_workflow.yml
.github/workflows/terraform_plan_job.yml
terraform/environment/kinesis-data-analytics.tf

Removes the precompiled Apache Flink Kinesis to Timestream Jar and builds the latest version in CI to ensure we always have the latest version.
Fixes Ticket: MET-49
A dedicated job checkouts and builds the artifact which will then on a plan and apply for environment will download and reference this .jar file.

Met 49 build java

---

.github/workflows/rotate_api_keys_workflow.yml

The nightly rotate key workflow currently breaks. This seems to be caused by not setting up terraform correctly as a step in the jobs.
https://github.com/ministryofjustice/opg-metrics/runs/7532681536?check_suite_focus=true
Add in the `hashicorp/setup-terraform` step specifying the version `1.2.3`.

Add `setup-terraform` to rotate api workflow

---

.github/workflows/rotate_api_keys_workflow.yml

Fix for Actions error stating `no valid credential sources`
The rotate keys action throws a credentials error here https://github.com/ministryofjustice/opg-metrics/runs/7552404479?check_suite_focus=true
This looks as though it does not have the AWS Credentials set to run the jobs correctly.
Use the same setup for configuring AWS CLI and credentials as the terraform plan and docker jobs to give it permission to act.
It may be nice to find a way to run this setup in a combined job so it reduces duplication on setup.

Add AWS CLI and Credentitals to taint job

---

.github/dependabot.yml
.github/workflows/rotate_api_keys_workflow.yml
.github/workflows/terraform_plan_job.yml

Upgrade `hashicorp/setup-terraform` github action and disabled stdout messages in TF.
Pass a missing TF variable `TF_VAR_timestream_artifact_name` to the taint jobs so no missing variable errors occur in TF.
If this works successfully then we need to look at whether we build the jar file in this workflow and get the name from it each time or whether we are happy with the string being passed as in this PR.
Also adds in a missing dependabot configuration for github actions

Taint workflow fix - Add missing `TF_VAR_timestream_artifact_name`

---

.github/workflows/openapi_ui.yaml

Fixes #61
The swagger ui job has been consistently failing for the last few weeks. This fixes the issue by upgrading the action that runs it.
Failures here: https://github.com/ministryofjustice/opg-metrics/actions/workflows/openapi_ui.yaml
Fixes Ticket: MET-58
Update the Github Action for checkout and swagger-ui to the latest versions.
Tested by running the workflow on a PR build to see if it passed successfully.

MET-58 Update swagger-ui and checkout action

---

terraform/environment/api-keys.tf

So we can start sharing case status metrics
Fixes Ticket: VEGA-1377
Copied the block above
I've looked at how the `trusted_service_access` module works
* N/A
* N/A
* N/A

Create service access for Sirius dev account

---

terraform/environment/kms.tf

Allow Sirius dev to decrypt KMS key so that it can access its secret for authentication
Supports Ticket: VEGA-1377
Again, following patterns of those before
N/A

Allow Sirius dev to decrypt KMS key

---

terraform/environment/api-keys.tf
terraform/environment/kms.tf

Give each account its own key and all have access permissions
Fixes Ticket: VEGA-1377
Giving each account a separate key for some permission isolation.
N/A
* N/A
* N/A
* N/A

Add API keys for all Sirius environments

---

terraform/environment/api-keys.tf
terraform/environment/kms.tf

Fix typo in role ARNs. They were missing the `role/` prefix
Fixes Ticket: VEGA-1377
Discovered during deployment
Role ARNs have a `role/` prefix to their name part

Fix typo in role ARNs

---

terraform/environment/api-keys.tf
terraform/environment/kms.tf

To send metrics from jenkins which the infra for lives in the shared accounts
Fixes Ticket: SP-1211

SP-1211 - Add API keys for shared prod and dev accounts #minor

---

.github/workflows/docker_job.yml
lambda/clsf-to-sqs/Dockerfile
lambda/clsf-to-sqs/Test.Dockerfile
lambda/clsf-to-sqs/src/requirements.txt
lambda/clsf-to-sqs/src/requirements_dev.txt
lambda/ship-to-opg-metrics/Dockerfile
lambda/ship-to-opg-metrics/src/requirements.txt
lambda/ship-to-opg-metrics/src/requirements_dev.txt
lambda/ship-to-opg-metrics/test.Dockerfile

Update the dockerfiles to use a custom base image to overcome out of date dependencies. Also updated the Python libraries used.
The latest [ECR Lambda from AWS](https://gallery.ecr.aws/lambda/python) is out of date and appears very slow at reacting to vulnerabilities.
I have instead decided to build our own based on the [Sirius notifier code](https://github.com/ministryofjustice/opg-sirius-infrastructure/blob/main/aws-health-notifier/Dockerfile).

Update docker lambda python image

---

kinesis_timestream_connector/connector/go.mod
kinesis_timestream_connector/connector/go.sum
kinesis_timestream_connector/connector/main.go
kinesis_timestream_connector/events/event.json
terraform/environment/api/openapi_spec.yaml

we are receiving data in the format { key: "value" } which causes an error in the json parser since it is not true json like { "key" : "value }  
Temporarily i've switched the parsing to a Yaml parser that can handle the lack of quotations. 

use yaml parser since the data we receive is not true JSON

---

.github/dependabot.yml

Remove dependabot config in place of renovate

Remove dependabot config in place of renovate

---

.github/workflows/build_and_upload_go_connector_artifact_job.yml

Should Stop the Go Lambda from falling over when it's trying to process events as C Go is not present in the new runtime.,

SP-1694 - Build Go Connector without c.Go #minor

---

terraform/environment/api-keys.tf

Grant access for MRLPA to use opg-metrics
Fixes Ticket: MLPAB-2961
- create keys for mrlpa dev, preprod and prod accounts
- let operator in those accounts use the key for now

MLPAB-2961 - create api keys for mrlpa

---

terraform/environment/api-keys.tf
terraform/environment/event_bus.tf
terraform/environment/versions.tf

MRLPA is using Eventbridge API destination targets to push metrics. The role used for API destinations needs to be permitted to invoke the api
Fixes Ticket: MLPAB-2904
- Add opg-metrics role to identifiers for api keys

MLPAB-2904 - allow mrlpa metrics role

---

terraform/account/terraform.tf
terraform/environment/terraform.tf

DynamoDB state locking is deprecated.
Fixes Ticket: MLPAB-2997
- use new state role and switch to state lockfile
- https://developer.hashicorp.com/terraform/language/backend/s3#state-locking

MLPAB-2997 - replace state role and use new lockfile approach for opg-metrics

---

terraform/account/data_sources.tf
terraform/account/kms_keys.tf
terraform/account/terraform.tf
terraform/modules/kms_key/.terraform.lock.hcl
terraform/modules/kms_key/data_sources.tf
terraform/modules/kms_key/kms.tf
terraform/modules/kms_key/kms_policy.tf
terraform/modules/kms_key/outputs.tf
terraform/modules/kms_key/terraform.tf
terraform/modules/kms_key/variables.tf

Use KMS customer managed keys for encrypting data in services
Fixes Ticket: MLPAB-2999
- add module for creating KMS CMKs
- add KMS key module instance for cloudwatch log groups

MLPAB-2999 add kms cmk for cloudwatch log groups

---

terraform/account/data_sources.tf
terraform/account/kms_keys.tf
terraform/account/network.tf
terraform/account/terraform.tf
terraform/account/variables.tf

KMS Key aliases need to be unique in the account
Fixes Ticket: MLPAB-2999
- rename key to include application name tag

MLPAB-2999 - rename key as it lives in a shared account

---

.github/workflows/path_to_live_workflow.yml
.github/workflows/pr_workflow.yml
.github/workflows/rotate_api_keys_workflow.yml
.github/workflows/terraform_plan_job.yml

use terraform_plan_job in api keys rotation workflow
Rotate API keys job fails to apply because the connector artifact for lambda is missing
Fixes Ticket: MLPAB-3019
- add apply_plan input to terraform plan job
- set apply_plan = false for pr workflows account and environment jobs
- set apply_plan = true for path to live account and environment jobs
- set apply_plan = true for api key rotate job
- add build artifact to api key job (job fails without artifact being present
- allow running api key rotate from github ui
~* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
~* [ ] I have added tests to prove my work~
~* [ ] The product team have tested these changes~

MLPAB-3019 - Fix rotate API keys job
