docs/architecture/decisions/0003-use-timestream-for-time-series-data-store.md
docs/architecture/decisions/0004-use-grafana-for-our-data-visualisation.md

Adds ADRs for Grafana and Timestream technology choices
Fixes Ticket: UML-1140
Uses the ADR tool to generate the files

Uml 1140 adr timestream grafana

---

scripts/pipeline/post_to_api/metrics.json
scripts/pipeline/post_to_api/post_to_api.py
scripts/pipeline/post_to_api/requirements.txt

Provide a script that will let us push a set of data to opg-metrics. This can be used to check that deployments are working.
Fixes Ticket: UML-1290
create a script to post to the metrics service AWS API Gateway

UML-1290 - Push data to opg-metrics using python

---

docs/architecture/README.md
docs/architecture/decisions/0005-aws-api-keys.md
docs/openapi/README.md
scripts/pipeline/post_to_api/.envrc
scripts/pipeline/post_to_api/post_to_api.py
terraform/environment/api-gateway.tf
terraform/environment/api-keys.tf
terraform/environment/api/openapi_spec.json

Build an authentication mechanism for Metrics API
Fixes Ticket: UML-1280
create a usage plan and API key for a demo trusted service

UML-1280 - Build an authentication mechanism for Metrics API

---

terraform/environment/.terraform.lock.hcl
terraform/environment/api-gateway.tf

UML-1501 - Enable api execution logging for opg metrics

---

.github/workflows/scanner.yml

Introduce action on a cron to scan this project for what packages are in use

add action for scanner

---

terraform/account/credentials.tf
terraform/environment/.envrc
terraform/environment/api-gateway.tf
terraform/environment/credentials.tf
terraform/environment/dns.tf
terraform/environment/locals.tf
terraform/environment/terraform.tfvars.json

Initial DNS entry attempt for api gateway

---

terraform/environment/api-keys.tf

Problem with quota not being configured correctly.
@charlesmmarshall are you able to apply locally for me to test this goes through okay?

Revert back to week for quota

---

terraform/environment/api-keys.tf
terraform/modules/trusted_service_access/README.md
terraform/modules/trusted_service_access/main.tf
terraform/modules/trusted_service_access/variables.tf

Adds secret manager api key

---

terraform/environment/api-keys.tf
terraform/modules/trusted_service_access/main.tf

Adds `opg-metrics-api-key/` specific prefix to secrets manager keys for better management.
Adds ualpa development key
Fixes Ticket: UML-1582

Adds opg-metrics specific prefix to secrets manager keys, add ualpa development key

---

.circleci/config.yml

Scheduled job failed because taint and apply ran at the same time.
Fixes Ticket: UML-1902
- add required job to ensure apply follows taint.

UML-1902 - require taint before apply

---

metadata.json

Adds new metadata.json file to repo

Add metadata file

---

terraform/environment/kinesis-data-analytics.tf
terraform/environment/kinesis-stream.tf
terraform/environment/kms.tf
terraform/environment/s3.tf

KMS is a little more involved. Rolling back changes to what it was before and unblocking further work.
Fixes Ticket: MET-55
Revert back to a state where KMS was not defined

Roll back of KMS key for tfesc warnings

---

.github/workflows/path_to_live_workflow.yml
.github/workflows/pr_workflow.yml
.github/workflows/terraform_plan_job.yml

download go artifact and set tf var

---

.github/workflows/path_to_live_workflow.yml
.github/workflows/pr_workflow.yml
.github/workflows/terraform_plan_job.yml
kinesis_timestream_connector/connector/main.go

Met 62 add logging to prove functionality

---

.github/workflows/terraform_plan_job.yml
terraform/environment/lambda.tf

Use download_go_artifact_path_name in tf go artifact name

---

terraform/environment/lambda.tf

change handler name to the executable that we create

---

kinesis_timestream_connector/connector/main.go
terraform/environment/api/openapi_spec.yaml
terraform/environment/kinesis-data-analytics.tf

- Reverts to JSON parser as YAML parser was not correctly unmarshalling invalid json
- Fixed the JSON package coming from API Gateway/Kenisis
- Disable JAVA App from running on startup now we have the lambda working.

Fix go app

---

.github/workflows/build_and_upload_go_connector_artifact_job.yml

SP-1646 - Update Build config for Go Lambda so it works in Lambda runtime #patch

---

.github/workflows/build_and_upload_go_connector_artifact_job.yml

Fix path to live failure when downloading artifact
Fixes Ticket: MLPAB-2776
- upgrade uploader

MLPAB-2776 - upgrade uploader

---

.github/workflows/rotate_api_keys_workflow.yml

Incorrect version being set for the rotate keys job
Fixes Ticket: MLPAB-2991
- parse terraform version

MLPAB-2991 - parse terraform version and setup for that

---

.github/workflows/rotate_api_keys_workflow.yml

use correct working directory

---

terraform/environment/api-gateway.tf

Log information about access and usage
Fixes Ticket: MLPAB-3001
- configure access log settings
- https://aquasecurity.github.io/tfsec/v1.28.13/checks/aws/api-gateway/enable-access-logging/
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_stage#access_log_settings

MLPAB-3001 - configure access logging

---

.github/workflows/terraform_plan_job.yml
terraform/environment/api-gateway.tf

Log information about access and usage
Fixes Ticket: MLPAB-3001
- configure access log settings
- https://aquasecurity.github.io/tfsec/v1.28.13/checks/aws/api-gateway/enable-access-logging/
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_stage#access_log_settings
- https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html

MLPAB-3001 - fix log format

---

terraform/environment/api-keys.tf

Receive metrics for the lpa-uid service
Fixes Ticket: MLPAB-3099
- create api keys for each lpa-uid account

MLPAB-3099 - create api keys for lpa-uid service

---

kinesis_timestream_connector/connector/main.go

I'm seeing some records rejected when putting events on lpa-store buses but I can't see the reason - this should (hopefully) give us a bit more to work from.
Enables MLPAB-2652

MLPAB-2652: Add more granular logging to lambda
